version: 2
updates:
  # Python packages
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
      # ignore all patch updates, they are too frequent
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    assignees:
      - janrito
      - risktoparkrageram
