name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    name: "Build and Test on ${{ matrix.python-version }}, experimental: ${{ matrix.experimental }}"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        experimental: [false]
        # include:
        #   - python-version: "3.13"
        #     experimental: true
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project
        run: uv sync --extra dev

      - name: Run Tests
        run: uv run ./run-tests.sh
