name: Tag & Release

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version-file: ".python-version"
          enable-cache: true

      - name: Install the project
        run: uv sync

      - name: Build binary wheel and a source tarball
        run: uv build --package vatvalidate --out-dir dist

      - name: Get new version
        run: echo "VERSION=$(uvx --from toml-cli toml get --toml-path pyproject.toml project.version)" >>$GITHUB_OUTPUT
        id: version

      - name: Tag with updated version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.VERSION }}

      - name: Create a GitHub release and upload artifact
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          generateReleaseNotes: true
          artifacts: './dist/vatvalidate-${{ steps.tag_version.outputs.new_version }}.tar.gz,./dist/vatvalidate-${{ steps.tag_version.outputs.new_version }}-py3-none-any.whl'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Latest tag
        uses: EndBug/latest-tag@v1

      - name: Publish to pypi
        run: |
          uv publish --token ${{ secrets.PYPI_TOKEN }}
